### PR TITLE
Self closing tags

### LINKED ISSUE #10: Tokenizer ignores self-closing-ness of tags
Failing test case:

https://github.com/zerobuzz/html-parse/blob/78fead5a145464cea4dc3c6e604d1cde6d6b2002/tests/Text/HTML/ParserSpec.hs#L102

I see two options to solve this:

1. Add an extra `TagClose` right after the self-closing tag in `parseTokens`.
1. Keep track of the self-closing-ness in `Token`, like `TagOpen Text [Attr] Bool`.

I prefer the first because it removes the special case locally in `parseTokens` and we never have to think about it again.  `[Token]` would be "more normalized" right after parsing.

### PR DESCRIPTION
**Pull request by fisx**
Fixes #10.  Obsoletes #11.

### CODE REVIEW

**Comment by fisx** [comment]
oops.  i'll look into the test failures.

**Comment by fisx** [comment]
ah.  that wasn't very hard.  :-)

**Comment by fisx** [comment]
now there is only the old 7.8 issue.  i propose to close #11 and merge #12.

**Comment by bgamari** [comment]
Sounds good to me.

**Pull request merged**
